version: '2.2'

services:
  wordpress:
    image: wordpress:latest
    container_name: wpdemo-wp
    restart: always
    ports: ['80:80']
    volumes:
      - './wp-data:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: wpdemo_phpmyadmin
    restart: always
    ports: ['12000:80']
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
